import Head from "next/head";

export const Headers = () => {
  return (
    <Head>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <meta name="referrer" content="no-referrer" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
