import { Box } from "@chakra-ui/react";
import { type NextPage } from "next";
import Head from "next/head";

// import { api } from "../utils/api";

import { Navbar, ProtectedRoute } from "../components";

const Home: NextPage = () => {
  return (
    <>
      <ProtectedRoute>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <meta name="referrer" content="no-referrer" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Box p={4}>Main Content Here</Box>
      </ProtectedRoute>
    </>
  );
};

export default Home;

